### ISSUE TITLE
Adb Core not work python 3 

### ISSUE THREAD

**Issue by taskinpy** [antdking/PyAdb#2]
i convert to 3 but not work 
Traceback (most recent call last):
  File "C:\Users\done\Desktop\xm_adb-master\adb_core.py", line 83, in <module>
    adb = AdbCore()
  File "C:\Users\done\Desktop\xm_adb-master\adb_core.py", line 10, in __init__
    self.connect()
  File "C:\Users\done\Desktop\xm_adb-master\adb_core.py", line 22, in connect
    self.write(command)
  File "C:\Users\done\Desktop\xm_adb-master\adb_core.py", line 43, in write
    self.connection.send(command)
TypeError: a bytes-like object is required, not 'str'

**Comment by antdking** [comment]
not supported, sorry!
